name: qr_attendance
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.3
  permission_handler: ^12.0.0+1
  fluttertoast: ^8.0.9
  qr_code_scanner:
    git:
      url: https://github.com/huypanha/qr_code_scanner.git
  meta_club_api:
    path: ../../data/meta_club_api
  core:
    path: ../../core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  hive_generator: