name: location_track
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocode: ^1.0.3
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  cloud_firestore: ^5.6.6
  meta_club_api:
    path: ../../data/meta_club_api
  core:
    path: ../../core
  offline_location:
    path: ../offline_location



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: